cc_library(
    name = "sample_sort",
    srcs = ["sample_sort.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//:config",
        "//utils:io_utils",
        "//utils:logger",
        "@com_google_absl//absl/container:btree",
        "@parlaylib//parlay:primitives",
        "@parlaylib//parlay/internal:get_time",
    ],
)
